#!/bin/bash
mkdir -p /workspace/examples/data/solar-panel/output

java -jar /workspace/examples/common/tools/maestro-2.3.0-jar-with-dependencies.jar\
  import -output /workspace/examples/data/solar-panel/output\
  --dump-intermediate sg1 cosim.json time.json\
  -i -vi FMI2 output-dir>debug.log 2>&1
