#!/bin/bash

# This script runs the co-simulation using Maestro 2.3.0.

echo "Executing the Digital Twin simulation..."

# Define the output directory
OUTPUT_DIR="./data/solar-panel-system/output"
mkdir -p "$OUTPUT_DIR"


java -jar ./tools/maestro-2.3.0-jar-with-dependencies.jar \
  import -output "$OUTPUT_DIR" \
  --dump-intermediate sg1 cosim.json time.json \
  -i -vi FMI2 output-dir > debug.log 2>&1


# Check if the simulation was successful
if [ $? -eq 0 ]; then
    echo "Simulation completed successfully."
else
    echo "Simulation failed. Check debug.log for details."
fi
